"""Render demo_data/CHEAT_SHEET.md from characters.py (+ output/*.json, if
present, for real "expect" outcomes).

Stdlib only -- runs with any Python, no venv/app deps needed:

    python demo_data\\render_cheat_sheet.py
"""
import json
import sys
from pathlib import Path

DEMO_DIR = Path(__file__).resolve().parent
OUTPUT_DIR = DEMO_DIR / "output"
CHEAT_SHEET_PATH = DEMO_DIR / "CHEAT_SHEET.md"

sys.path.insert(0, str(DEMO_DIR))
from characters import (  # noqa: E402
    CHARACTERS,
    DEMO_CLINICIAN,
    DEMO_PASSWORD,
    demo_email,
)

ARRIVAL_MODE_LABEL = {
    "ambulance": "Ambulance", "car": "Car", "walk_in": "Walk-in",
    "public_transport": "Public Transportation", "wheelchair": "Wheelchair", "other": "Other",
}


def load_output(name: str) -> dict:
    path = OUTPUT_DIR / f"{name}.json"
    if not path.exists():
        return {}
    return {row["external_id"]: row["output_payload"] for row in json.loads(path.read_text(encoding="utf-8"))}


def triage_section(character: dict, outcomes: dict) -> str:
    t = character["triage"]
    v = t["vitals"]
    complaint = t["complaints"][0]["token"]
    lines = [
        "**Triage (`/triage/`)**",
        f"- Age: `{t['age']}`  Sex: `{t['sex']}`  Arrival mode: `{ARRIVAL_MODE_LABEL[t['arrival_mode']]}`",
        f"- Complaint: `{complaint}`",
        f"- Vitals: HR `{v['hr']}`  SBP `{v['sbp']}`  DBP `{v['dbp']}`  RR `{v['rr']}`  "
        f"O2 `{v['o2']}%`  Temp `{v['temp']}°{v['temp_unit']}`",
    ]
    out = outcomes.get(character["external_id"])
    if out:
        if out.get("model_refused"):
            lines.append(f"- **Expect:** refused — {out.get('refusal_reason')}")
        else:
            lines.append(f"- **Expect:** {out.get('predicted_level')}")
    lines.append(
        f"- **Or demo the note extractor:** click \"{character['display_name']}\" under "
        f"\"Demo characters\" in the Triage intake tab (or paste this note): "
        f"*\"{character['clinician_note']}\"* — runs live against Gemini, no pinned "
        f"fallback, so a working `GEMINI_API_KEY` must be reachable at demo time."
    )
    return "\n".join(lines)


def stroke_section(character: dict, outcomes: dict) -> str:
    s = character["stroke"]
    flags = ", ".join(
        name for name in ("Smoking", "Alcohol_Intake", "Family_History", "Heart_Disease", "Diabetes")
        if s[name]
    ) or "none"
    lines = [
        "**Stroke risk (`/stroke/`)**",
        f"- Age: `{s['Age']}`  Gender: `{s['Gender']}`  BMI: `{s['BMI']}`",
        f"- Blood pressure: `{s['Blood_Pressure_Systolic']}/{s['Blood_Pressure_Diastolic']}`  "
        f"Cholesterol: `{s['Cholesterol']}`  Glucose: `{s['Glucose_Level']}`",
        f"- Physically active: `{'Yes' if s['Physical_Activity'] else 'No'}`  Risk factors ticked: {flags}",
    ]
    out = outcomes.get(character["external_id"])
    if out:
        pred = out["prediction"]
        lines.append(f"- **Expect:** {pred['risk_category']} ({pred['risk_probability_percent']}%)")
    return "\n".join(lines)


def emc_section(character: dict, outcomes: dict) -> str:
    m = character["emc"]["metadata"]
    symptoms = ", ".join(character["emc"]["symptoms"])
    lines = [
        "**EMC (`/emc/`)**",
        f"- Patient name: `{m['patient_name']}`  Patient ID: `{character['external_id']}`  Age: `{m['patient_age']}`",
        f"- Clinic: `{m['clinic_name']}`, {m['clinic_address']}",
        f"- Attending clinician: `{m['attending_clinician_name']}`  Reg. no: `{m['clinician_registration_no']}`",
        f"- Authorised leave days: `{m['authorized_medical_leave_days']}`  "
        f"Diagnosis disclosure consent: `{'Yes' if m['diagnosis_disclosure_consent'] else 'No'}`",
        f"- Symptoms to tick: {symptoms}",
    ]
    out = outcomes.get(character["external_id"])
    if out:
        pred = out["prediction"]
        lines.append(
            f"- **Expect (ML classifier, before the clinician review step):** "
            f"{pred['primary_predicted_diagnosis']} ({pred['prediction_confidence_percentage']}%)"
        )
    return "\n".join(lines)


def main():
    outcomes = {
        "triage": load_output("triage"),
        "stroke": load_output("stroke"),
        "emc": load_output("emc"),
    }

    parts = [
        "# VitalHealth demo cheat sheet",
        "",
        "Generated by `demo_data/render_cheat_sheet.py` from `demo_data/characters.py` "
        "-- do not hand-edit, regenerate instead.",
        "",
        "Eight mock patients, each with a scenario in all three apps. \"Expect\" lines are "
        "the real, currently-loaded model's own output (from `demo_data/output/*.json`); "
        "if a section has no \"Expect\" line, the compute script for that app hasn't been "
        "run yet -- see `demo_data/README.md`.",
        "",
        "## Logins",
        "",
        "Created by `seed_db.py`, which also marks each character's seeded records as "
        "theirs -- so a character's dashboard is already populated at first login.",
        "",
        "| Who | Email | Password |",
        "| --- | --- | --- |",
        f"| Clinician ({DEMO_CLINICIAN['display_name']}) | `{DEMO_CLINICIAN['email']}` "
        f"| `{DEMO_CLINICIAN['password']}` |",
    ]
    for character in CHARACTERS:
        parts.append(
            f"| {character['display_name']} | `{demo_email(character['external_id'])}` "
            f"| `{DEMO_PASSWORD}` |"
        )
    parts.append("")

    for character in CHARACTERS:
        parts.append(f"## {character['display_name']} (`{character['external_id']}`)")
        parts.append("")
        parts.append(character["note"])
        parts.append("")
        parts.append(triage_section(character, outcomes["triage"]))
        parts.append("")
        parts.append(stroke_section(character, outcomes["stroke"]))
        parts.append("")
        parts.append(emc_section(character, outcomes["emc"]))
        parts.append("")

    CHEAT_SHEET_PATH.write_text("\n".join(parts), encoding="utf-8")
    print(f"Wrote {CHEAT_SHEET_PATH}")


if __name__ == "__main__":
    main()
