"""Generate apps/Jace/static/demo_character_seeds.js from characters.py.

Stdlib only -- runs with any Python:

    python demo_data\\sync_jace_seeds.py

Kept as a separate array/file from Jace's own built-in `seeds` (in
apps/Jace/static/app.js) rather than merged into it, so
apps/Jace/tests/test_intake_api.py::test_pinned_extractions_cover_all_appjs_seeds
(which hard-asserts exactly 10 built-in seeds, each pinned) stays untouched
and passing -- these 8 are deliberately unpinned, live-extraction-only (see
demo_data/README.md).

The generated file is committed, not gitignored: apps/Jace/static/index.html
loads it directly via a <script> tag, so Jace's frontend needs it present on
a fresh clone, not only after someone thinks to run this script.
"""
import json
import sys
from pathlib import Path

DEMO_DIR = Path(__file__).resolve().parent
ROOT = DEMO_DIR.parent
OUTPUT_PATH = ROOT / "apps" / "Jace" / "static" / "demo_character_seeds.js"

sys.path.insert(0, str(DEMO_DIR))
from characters import CHARACTERS  # noqa: E402


def main():
    seeds = [
        {
            "label": character["display_name"],
            "note": character["clinician_note"],
            "vitals": character["triage"]["vitals"],
        }
        for character in CHARACTERS
    ]
    body = json.dumps(seeds, indent=2)
    OUTPUT_PATH.write_text(
        "// Generated by demo_data/sync_jace_seeds.py from demo_data/characters.py.\n"
        "// Do not hand-edit -- regenerate instead.\n"
        f"window.DEMO_CHARACTER_SEEDS = {body};\n",
        encoding="utf-8",
    )
    print(f"Wrote {len(seeds)} character seeds to {OUTPUT_PATH}")


if __name__ == "__main__":
    main()
